### ISSUE TITLE
StackdriverTrace Exporter: support alternate endpoint

### ISSUE THREAD

**Issue by mandarjog** [census-instrumentation/opencensus-cpp#340]
SD trace exporter [hardcodes](https://github.com/census-instrumentation/opencensus-cpp/blob/57cbb8b9950765cb304e36df7753899a84b476ba/opencensus/exporters/trace/stackdriver/internal/stackdriver_exporter.cc#L40) ` kGoogleStackdriverTraceAddress = "cloudtrace.googleapis.com"` This should be configurable thru `StackdriverOptions`

Usecases
1. Send to a staging endpoint.
2. Use in integration tests.

@g-easy  @bogdandrutu

**Comment by g-easy** [comment]
We could do something like https://github.com/census-instrumentation/opencensus-cpp/pull/341

This lets you supply a Stub rather than a string, which is how Java does it: https://github.com/census-instrumentation/opencensus-java/blob/bf92dbaeaf7295618939c940cd22095eac94443a/exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceConfiguration.java#L144

The downside is we either have to change the API of Register() to take an rvalue: https://github.com/census-instrumentation/opencensus-cpp/pull/341/files#diff-81d537b18f54410b7a19158cd7b44e20R61

Or we put a plain pointer in StackdriverOptions and document it as transferring ownership, so Register doesn't break.

@bogdandrutu what do you think we should do API-wise?

**Comment by g-easy** [comment]
Fixed by #341.
